messages:
  playerjoin: '%player% joins the server'
  playerleave: '%player% leaves the server'
  playerkick: '%player% was kicked from the server (%reason%)'
  playerdeath: '%killed% was killed by %killer%'
chat-prefix:
  player: '%player% >> %message%'
  server: 'Server >>'
automessages:
  -[AutoMessage] Welcome to the server
  -[AutoMessage] Welcome to the server
  -[AutoMessage] Welcome to the server