recipes:
  nametag: enable
  netherstar: enable
  saddle: enable

names:
  nametag: Nametag  
  netherstar: Netherstar
  saddle: Leather Saddle
  
descriptions:
  nametag: Add some personality to the game
  netherstar: Twinkle, twinkle little star
  saddle: Useful for riding a pig