information:
  start-lines:
  - '******************************************'
  - 'Hints for Information Plugin'
  - '******************************************'
  - ' >> /info-toggle: hide/show info panel'
  - '******************************************'
  enabled: true
  title: Information
  lines:
  - 'Server: %server%'
  - 'Real time: %realtime%'
  - 'World time: %worldtime%'
  - 'Player online: %online_players%'
  - 'Difficulty: %difficulty%'
  - 'Plugins: %plugin_list%'
